[project]
name = "local-llm"
version = "0.1.0"
description = "Simple RAG implementation with LangChain and Ollama"
readme = "README.md"
authors = [
    { name = "Khoi Nguyen", email = "khoinet9690@gmail.com"}
]
requires-python = ">=3.10,<4.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "langchain>=0.2.0",
    "langchain-community>=0.2.0",
    "langchain-ollama>=0.1.0",
    "langchain-core>=0.2.0",
    "faiss-cpu>=1.7.4",
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "pydantic>=2.0.0"
]

[project.optional-dependencies]
# Dependencies needed for development, testing, and formatting
dev = [
    "pytest==7.4.2",
    "black==23.7.0",
    "flake8==6.0.0"
]

[tool.poetry]
packages = [
    { include = "src"}  # <-- Use the dictionary structure here
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"